[server]
    service_name="user.db.rpc"
    port = "7071"
    timeout = 5000

[database]
    name = "mciro_user_db"
    dsn = "root:_d6JE49FQsWT@tcp(39.108.101.229:3433)/micro_user?charset=utf8mb4&parseTime=True&loc=Local"
    port = 3306
    max_conn = 100
    max_open = 10
    timeout = 2000
