jwt_secret_key = "4jAwLIKNF9llT1xlQb3JuxSseELYAj5Y"
[server]
    service_name="user.logic.http"
    port = "7070"
    timeout = 5000

[[server_client]]
    service_name="user.db.rpc"
    address="localhost:7071"

[database]
    name = "mciro_user_db"
    dsn = "root:_d6JE49FQsWT@tcp(39.108.101.229:3433)/micro_user?charset=utf8mb4&parseTime=True&loc=Local"
    port = 3306
    max_conn = 100
    max_open = 10
    timeout = 2000

[wechat]
    app_id="wx2bae646e7f57c505"
    secret="c8514ef6cc67827f74759958342861a9"